source 'https://rubygems.org'

gem 'rails', '3.2.15'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'


gem 'mysql','2.8.1'
gem "paperclip", "~> 4.2"
gem 'remotipart', '~> 1.2'
gem 'will_paginate', '~> 3.0'
gem 'rabl-rails'
gem 'chartkick'

gem 'redis', '~> 3.0'
gem 'puma', '~> 3.0'

gem 'execjs'
gem 'rake','10.4.0'
gem 'therubyracer', '0.10.2'
gem 'prawn', '1.3.0'
gem "prawnto_2", :require => "prawnto"
gem 'declarative_authorization', :source => "http://gemcutter.org"
gem 'delayed_job_active_record'
#gem 'rails-erd'
gem 'rails-erd', '~> 1.4.0'
gem 'ruby_parser', '~> 3.6.6'
gem 'bootstrap-generators', git: 'git://github.com/decioferreira/bootstrap-generators.git'
gem 'pdfkit',:source => "http://gemcutter.org/"
gem 'wkhtmltopdf-binary',:source => "http://gemcutter.org/"
gem "font-awesome-rails"
gem 'fastercsv', '~> 1.5'
gem 'will_paginate', '~> 3.0'
gem 'will_paginate-bootstrap'


#gem 'prawn'
#gem 'prawn_rails'
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'jquery-rails'
  gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails' 
 
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem "bcrypt-ruby", :require => "bcrypt"

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'
#https://github.com/pdfkit/pdfkit.git

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'